"""Initial commit

Revision ID: ed88c4a88785
Revises: 
Create Date: 2023-05-24 13:44:18.891335

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed88c4a88785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Book',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('in_stock', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('genres', sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column('authors', sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column('release_date', sa.Date(), nullable=True),
        sa.Column('writing_date', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Book')
    # ### end Alembic commands ###
