"""fix column name

Revision ID: 4a6713f02236
Revises: ed88c4a88785
Create Date: 2023-05-24 17:40:52.336714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a6713f02236'
down_revision = 'ed88c4a88785'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Book', sa.Column('author', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('Book', 'authors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Book', sa.Column('authors', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('Book', 'author')
    # ### end Alembic commands ###
